#
# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#
# https://www.baeldung.com/hikaricp
# https://www.baeldung.com/spring-boot-hikari
# https://github.com/brettwooldridge/HikariCP/wiki/Spring-Hibernate-with-Annotations
#
server:
#  port: 8888
#  servlet:
#    context-path: /auth

spring:
  datasource:
    url: jdbc:mariadb://localhost/outboundengine?autoReconnect=true&tcpKeepAlive=true
    jdbc-url: ${spring.datasource.url}
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      transaction-isolation :
      idleTimeout: 300000
      maxLifetime: 3600000
      maximumPoolSize: 5
      minimumIdle: 1
      poolName: outboundengine
      registerMbeans: false
      leakDetectionThreshold: 30000

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        #  sql debugging values
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace

  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health, status, loggers, logfile, metrics, mappings, scheduledtasks, env, jolokia
    jmx:
      exposure:
        include: health, status,  metrics, scheduledtasks, shutdown
