/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.tec.auth;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.transaction.annotation.EnableTransactionManagement;

@SpringBootApplication
@EnableTransactionManagement
// configs need to be here and not on the spring boot annotation...
@ComponentScan(basePackages ={"org.tec.auth.config", "org.tec.auth.svc"})
@EntityScan(basePackages = {"org.tec.auth.entity"})
@EnableJpaRepositories(basePackages = {"org.tec.auth.repository"})
@SuppressWarnings("PMD.UseUtilityClass")
public class AuthApplication {
    public static void main(final String[] args) {
        SpringApplication.run(AuthApplication.class, args);
    }
}
